feat: adds PING support to momento proxy resp impl
pelikan-io/pelikan pull request #6
Opened 2022-12-29 19:00 UTC by eaddingtonwhite

2022-12-30 16:04 UTC, brayniac requested changes

2022-12-30 16:04 UTC, brayniac commented on src/protocol/resp/src/request/ping.rs
> +// Licensed under the Apache License, Version 2.0
let's add the Pelikan Foundation LLC as the copyright holder w/ 2022 year.

2022-12-30 16:04 UTC, brayniac commented on src/proxy/momento/src/protocol/resp/ping.rs
> +// Licensed under the Apache License, Version 2.0
Same here

2022-12-30 16:04 UTC, brayniac commented on src/proxy/momento/src/protocol/resp/ping.rs
> +const PONG_RSP: &[u8; 7] = b"+PONG\r\n";
Is there a reason this wasn't implemented in the RESP protocol instead?

2022-12-30 16:04 UTC, brayniac commented on src/proxy/momento/src/protocol/resp/ping.rs
> +    let mut response_buf = Vec::new();
I think you can do all this w/o allocating here

2022-12-30 16:04 UTC, brayniac commented on src/proxy/momento/src/protocol/resp/ping.rs
> +    SESSION_SEND_BYTE.add(response_buf.len() as _);
`PONG_RSP.len()` should work too?

2022-12-30 16:04 UTC, brayniac commented on src/proxy/momento/src/protocol/resp/ping.rs
> +    if let Err(e) = socket.write_all(&response_buf).await {
i think you could `.write_all(PONG_RSP)` here?

2022-12-30 16:07 UTC, brayniac commented
Overall, this works. I think it'd be cleaner for the pong response to be part of the RESP protocol implementation, as that will be useful when we add a redis compatible backend.

2026-08-18 06:51 UTC, thinkingfish commented
Closing: the momento proxy was removed from this repo in #152, so this change no longer has a target. Thanks for the contribution.

2026-08-18 06:51 UTC, closed without merging